
  # After registering a name on build.snapcraft.io, commit an uncommented line:
  name: morg
  version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
  summary: A cli tool for organizing music using tags # 79 char long summary
  description: |
    This is my-snap's description. You have a paragraph or two to tell the
    most important story about your snap. Keep it under 100 words though,
    we live in tweetspace and your description wants to look good in the snap
    store.
  base: core22
  grade: devel # must be 'stable' to release into candidate/stable channels
  confinement: devmode # use 'strict' once you have the right plugs and slots
  architectures:
    - build-on: amd64
    - build-on: arm64
  parts:
    morg:
      # See 'snapcraft plugins'
      plugin: dotnet
      dotnet-build-configuration: Release
      source: .
      build-packages:
          - dotnet-sdk-8.0
      stage-packages:
          - libicu70
#          - dotnet-sdk-8.0
  apps:
    morg:
      command: morg
  #apps.morg.enviroment:
    
